# -*- coding: utf-8 -*-
"""TrabFinal-DAGE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zSb9Tapqu2idoESLjmEXPQres3TicYLi

#Trabalho Final de Desenvolvimento de Aplicações Geoespaciais
Leandro Medeiros

O objetivo foi desenvolver uma aplicação que apresentasse as Unidades Básicas de Saúde da Familia da Cidade de Piripiri-PI, destacando seus horários de funcionamento, e também a posição do usuário e a rota até estas unidades.

Instalando Foilium, Datetime e configurando a hora local.
"""

!pip install --upgrade folium
import folium
from datetime import datetime
import pytz

tz_PI = pytz.timezone('America/Fortaleza')
datetime_PI = datetime.now(tz_PI)
hora = int(datetime_PI.strftime("%H"))
dia  = datetime.today().weekday()

from folium.plugins import MarkerCluster
from folium.plugins import LocateControl

"""#Configurando os displays dos horários de funcionamento."""

#Manha
ttp01='<b>UBSF 01 VISTA ALEGRE<br>Rua Professor Bem, 1916.</b><br><br> Atendimento: <br> Segunda a sexta: 7h a 11h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp17='<b>UBSF 17 FONTE DOS MATOS<br>Rua Jose Angelo Ferreira, 660.</b><br><br> Atendimento: <br> Segunda a sexta: 7h a 11h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp03='<b>UBSF 03 - PRADO <br>Rua Arnold Pires Fernandes, 620.</b><br><br> Atendimento: <br> Segunda a sexta: 7h a 11h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp04='<b>UBSF 04 - PACIENCIA <br>Rua Acelino Rezende, 1584.</b><br><br> Atendimento: <br> Segunda a sexta: 7h a 11h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp19='<b>UBSF 19 - ESTACAO <br>Rua Luis Gonzaga A. Filho, 400.</b><br><br> Atendimento: <br> Segunda a sexta: 7h a 11h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp09='<b>UBSF 09 - FLORESTA <br>BR-222, 865.</b><br><br> Atendimento: <br> Segunda a sexta: 7h a 11h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp05='<b>UBSF 05 - RECREIO <br>Rua Quirino de Sousa Meneses, 364. </b><br><br> Atendimento: <br> Segunda a sexta: 7h a 11h. <br> Sabado: Fechado. <br> Domingo: Fechado.'

#Tarde
ttp21='<b>UBSF 21 - PACIENCIA 2<br>Rua Ver. Cristino das Chagas Mendes, 1030.</b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp29='<b>UBSF 29 - PETECAS III e IV<br>Rua Projetada Z, sn.</b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp18='<b>UBSF 18 - CENTRO<br>Rua Vicente A. Assuncao, 63.</b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp08='<b>UBSF 08 - GERMANO <br>R. Enóque Monte, 466.</b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp07='<b>UBSF 07 - CAIXA DAGUA <br>R. Cap Manoel de Oliveira, 300. </b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp13='<b>UBSF 13 - MATADOURO <br>R. Cidade de Esperantina, 1485 </b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp06='<b>UBSF 06 - SAO JOAO <br> Rua Emidio Mendes de Souza, 200 </b><br><br> Atendimento: <br> Segunda a sexta: 13h a 15h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp15='<b>UBSF 15 - CONJUNTO <br> Av. Aderson Alves Ferreira, 3150.</b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'
ttp02='<b>UBSF 02 - SANTA MARIA <br> Rua José A. de Assunção, 330.</b><br><br> Atendimento: <br> Segunda a sexta: 13h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'

#integral
ttp20='<b>UBSF 20/24 PETECAS/CRIOLI <br> Rua Projetada Cento e Trinta e Nove, sn.</b><br><br> Atendimento: <br> Segunda a sexta: 07h a 17h. <br> Sabado: Fechado. <br> Domingo: Fechado.'

"""#Configurando os Popups"""

#Manha
ppp01='<b>UBSF 01 - VISTA ALEGRE</b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3e_t0mYCTqLeoEt5U5ll1E15ONq1FpDRa4Y0mIKlPXh9CU3mQ5_ynfwyTY4OBBSQ3yDzOdwz0HZZtGscrLTHlzHTGv7QKmXyFlIJEsRWh5Tryjj75YEo5dhH9YjB4aJgIV-WasUcPKZ3s3He8Lp1wF_5g=w720-h425-no?authuser=0" style="width:250px;height:200px;"><br><a href="https://turismo.curitiba.pr.gov.br/conteudo/jardim-botanico/1674">Acesse o site!</a> ', 
ppp17='<b>UBSF 17 - Fonte dos Matos</b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3cPeR2j9xuF4sgDZnvuwJSPn3aqYm85wRDcbey6pk-vS-q9QPDnhhVXV5Q1gIz7I7Njzx8tD1XUNK6dj-YKyQIPYmoPoUN6J9BOt32HNwmbeog-qTJNANQ-xpGCU6ZaY1y0aWL4B6bBht5C7ixXaLGXdQ=w548-h376-no?authuser=0" style="width:250px;height:200px;"><br><a href="https://turismo.curitiba.pr.gov.br/conteudo/jardim-botanico/1674">Acesse o site!</a> ', 
ppp03='<b>UBSF 03 - Prado </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3e7ZXgDIducEkr9HjsmhGyaajv4M90Ji6gccQdfiiqVRvLQGGh7kFreZSPdL7kOHFs9AOOCgpJc617lr62JWb3evlN6l-JZhfrwH61q0HcOw4AeRKi2d1KpVGcbYNZJRC4G2_fRYRtLX_pcjr9DutelqA=w524-h415-no?authuser=0" style="width:250px;height:200px;"><br><a href="https://turismo.curitiba.pr.gov.br/conteudo/jardim-botanico/1674">Acesse o site!</a> ', 
ppp04='<b>UBSF 04 - Paciencia </b><br><img src="https://i0.wp.com/www.transamerica.com.br/blog/wp-content/uploads/2019/02/image1-3.jpg?resize=768%2C511&ssl=1" style="width:250px;height:200px;"><br><a href="https://turismo.curitiba.pr.gov.br/conteudo/jardim-botanico/1674">Acesse o site!</a> ', 
ppp19='<b>UBSF 19 - Estacao </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3dapW9C1pO4JYZhoZTouUu4EMTbECaygAgHB-W6rPfNiJh7JHoXtvCROB_LbuwYj7MPJaYrYTD3D_55MctmughWoHhFoV6MHJtw5Fp5jr9nE97JIqFJytsWeNjioSuJ3KRKaEwnQyhdMKxDAOEtb5A9oQ=w837-h628-no?authuser=0" style="width:250px;height:200px;"><br><a href="https://turismo.curitiba.pr.gov.br/conteudo/jardim-botanico/1674">Acesse o site!</a> ', 
ppp09='<b>UBSF 09 - Floresta </b><br><img src="https://i0.wp.com/www.transamerica.com.br/blog/wp-content/uploads/2019/02/image1-3.jpg?resize=768%2C511&ssl=1" style="width:250px;height:200px;"><br><a href="https://turismo.curitiba.pr.gov.br/conteudo/jardim-botanico/1674">Acesse o site!</a> ', 
ppp05='<b>UBSF 05 - Recreio </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3fkLFOotkllI70e1arzChkYpjkYbNWsi65gynh9GDVOrWrkr5ZhbhAZpUDubuWvrP1VVDW9OzMCsFNh8U3i2vrjE32CzLDmYCwW7GIh1VUXOwglYk8oVtc97Fr4f3gcva1Vw6uNmdM6D2uZ6yOaQB-_qA=w658-h566-no?authuser=0" style="width:250px;height:200px;"><br><a href="https://turismo.curitiba.pr.gov.br/conteudo/jardim-botanico/1674">Acesse o site!</a> ', 
#Tarde
ppp21='<b>UBSF 21 - Paciencia 2 </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3dwLd3SNCutxThquCDUAR1BeR60su0eBEbUPJvb0uF33MdhBP0bIFBJdmMQLkHCo8vSP2So_PkIkfOTi3wR9_9si-7obE7rMSJZaMJaDo9AvIzRkW9VS3U7Ou6fJmzdvPjIvZJfCoA8WhbfvRNyxoh7sQ=w635-h590-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/">Acesse o site!</a> ', 
ppp29='<b>UBSF 29 - Petecas III e IV </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3eY-vug0hPBzhnRteEw9h4zENlUYEf3CUp51ImyEEyQdMTFhvDhC5my08RDXxiV4Ms2JpzPVNC3ZRiEVybtIyOKLcnskA1vRNffhbNWH04wG7NPML1VEYkHRyMra9VcZVjYzXeNyyI4sqJxWhqVc3t40g=w685-h469-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/">Acesse o site!</a> ', 
ppp18='<b>UBSF 18 - Centro </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3eXDzTXvOwlW4kJMXZ51tgWgYTjjbbUl49ZgzIR2tkElBP5hRJFt4UIpS07c3mYjsKfeSuvq8ie8lfGpo62xuEr7hlI-4nau8mIM9IbFhWRCc7OsvFN0Un7dpa8fQhpYIsX2iQ1aygBeZ3NH0AljN3afg=w495-h429-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ', 
ppp08='<b>UBSF 08 - Germano </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3f87weEqMp2aKFC14kFY9gt4hH2YOWgMOlKKYKT4rta-Imq7rK_6B2orhZ1oqnIGjvnKrzCtlKZAhbYXnp2cUHFXDhcVtzLqcMSqhc1OX09amaSvvGI-1_KUanpqeThaI6a-RpOAP8UL_2M0prR6n-7iw=w809-h645-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ', 
ppp07='<b>UBSF 07 - Caixa dAgua </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3fMoqScZny3kIOC3bZoCIrJXJ_PgLie2R4G6xZTC7-fW1f57IKHbRQYaJMaD9ujxDln7mEtVbBbbCCox-r1YeuBZE6XNuJNPR5om679_1ZO68DylTKZrzUb5vKPMXOtbrXxMFRQ18bZ6EBh15pww8N84w=w830-h650-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ', 
ppp13='<b>UBSF 13 - Matadouro </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3fBypLIOc6D1xeHERvHcgACTJJfWP13x_yv628tmGIoDRtwTyo7mj5Im1Kg_OzoOwu5Lr85EpURXyj74byux_40gC4kqM_6iA1wfl3nJDbvGc8BY4Tr1NjtxGuA0zWIfW2mxKktnzAAwYxhB5U-bvGkZg=w663-h418-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ', 
ppp06='<b>UBSF 06 - Sao Joao </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3cEUiPitaSpwdcpM7XRwrOqlEcEYyWbtC4rLMh7M3KN0Sp4woLCTyuapX0RrMUkKeRTLi5ctWPwJ09rnDaXGcRMHgNBw1LuyPEH5NKdo5TbhX_rZtpqFGazFM90vMsUQHxSH1I6Lp_uejEK9H4ROkqewA=w811-h594-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ', 
ppp15='<b>UBSF 15 - Conjunto </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3ds5Cb1PEJnvKXV0qSb6X6XkhxmGNUmWLamXv83R2vVFRN5ejmDPcyOmQgAU3daECtFRwwl1dA4_btsQZ5QC8RHpEJLR7R4h75VTg7kJK_ZGXfGfBf4l8n_QuYPctEOY6Ksbsm9xBbHJPVWL3wTzVZbnQ=w491-h389-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ', 
ppp02='<b>UBSF 02 - Santa Maria </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3eK-hEQ2EvwBzgszPlz70OBOtozzRvl85PMFJEIxDTT2HHvy_EIQbGFdOuxT1Vxxxy008HKO7Y9dQjkFZBg1N1E75sb9IAq83nxH5cVE1l3baJBXbkbMSTwQAaHzPLTt_JtWb4WWwbTvOIJiTJ7O2t9Vg=w608-h494-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ', 
#Integral
ppp20='<b>UBSF 20/24 - Petecas/Crioli </b><br><img src="https://lh3.googleusercontent.com/pw/ACtC-3dW6NElcmOqHjC0GCXMDicchddIzPvSHfAVFYRBaTsNIJAYboC5oTwAcGu5-Pt9AsF372Gwdjddi2xjE41IWplQg66lM3eYuNkPNOFe8F0Gty5394y18pQPo_qs8RWHTXewmjHdklE2w8uK9p53mmEkoA=w408-h240-no?authuser=0" style="width:250px;height:200px;"><br><a href="http://www.piripiri.pi.gov.br/site/?start=24">Acesse o site!</a> ',

"""#importando os markers do Google Fotos"""

m = folium.Map (location = [-4.275,-41.78],
               tiles = 'OpenStreetMap',
               zoom_start =  13.5,
               attr = 'Colaboradores do OpenStreetMap e Alunos de CartoUFPR/ Dados IPPUC' 
               )
cluster = folium.plugins.MarkerCluster().add_to(m)


#URL dos MARKERS - Manha

a01 = folium.features.CustomIcon('https://lh3.googleusercontent.com/keJXoeoiVF29hlK4J5DwOWf__NQ4cfgL0-mrAvCdUaUczl6RDL4fAnmqeBHqKTTlskekrrf0TgJ_I-40ng2F8kbVyt66tDXzZnN0bRi7zSaiFC_LPcTad-4u11hz1dwwaY5z8MnRnkG0_FpIzKImhm1RP2KbYayssXMQTaSIMFFfRpnfNDoao7f5fNjfSc_azilHBqvvVT8C1VjKDkX5KuvxAzyRgila5CmOsve6jblY5z-qY3rUQqHm3EsniwAIX7aaOtZMKJOkj5CY_7cFt8SjxreBxB1RP1iQgehlDANzMbQQtP265AMR1vFfgJyXM4MK-oLkZScvCPyUkzgtS_xkjc3JZ-e1texE-jx7R9nZaEM4Yvy_Q2zjdivFkVQwW5yiaADa5L_eTJWTW_wjQTNHv5QKgn1uHQn0kRCVz8wBaz0iNIM4qwmisc9GhUJ26Mvs49C2-en-Wxvgp56Gp_M6JssYo6W_6pM7-z7knYbG1isHn9hIIQcWKmrlTt71HmJwhNAyRKkx8arJZMMklN3ySXA9dQBYS8i_q2-AmunzYY8NmxwstA4qmnf96kMlBVgpBTlplBZVF0dnNAi3M98wlKyiXYrNYnuAkmoDnlcV8zm5qmji5pN83IxHk_0pyBQiyl9K1yI6PPAQVAlnl0fXEfZjGWpAV2cbl2f7HkHV34W1pBSc9aOdMxnDPQ=w71-h78-no?authuser=0'
,icon_size=(60, 60))

a17 = folium.features.CustomIcon('https://lh3.googleusercontent.com/ZPVxWEJ1ts5jul7ITQnwDOevuMPFHqnnKVhnqeBUpcM6RyJlvMgXJomrkLJaUbc_gHqgJaWft6s37unVBTB0S6gUPmqy0sV2WuT0iqhynPDqDqK-sbd58ZbnPbjfC-Ns8mdCQclFL87rcQydApqTdMM2jIGDKN4-BryJ4o9IfVRvgvrkJRfKQ9C1uQceh-UVGxGww-02xyaqFljfbivPYwRHWTw4xCCeTjTQyTwpYc1lzc2ecg0LyIl-w-uDyV7WmGAyMLAiDV72J3FHEdrBCbW_lFg3vT-VrfqxQX6ig7f00wZgXgFJNHDTO-swiR8wsvmT0IJ8lVzIg8aj1BSsY3yEIVdlPcfJj2n1wPtYOOg_-lsS7U6dW13py3OPXRXaPe8aaxCmoqPWXHKQpqNU9qIWlzESwT6cny2h91oabt7XUErohGYhnBxb6ShOgPTkrt4vXaoEa0n3ourpNx8VR-vsvyzNgD36acD3eMrt2JGqpgKFlvtKWg1UG1qPmV6KfyIBMLqV5Iv9hBLJjgczsK1BiYvKhVYbaBxKunLFQXWNesV1bAP_EFnouONoAYSLnyUHKIJ5QKCuFjMYl9SDWSN5J2wxi_kSvVU1jXfd5kSe11xjSvoXleho4K3PXoRslquy06kHiwljAgpl5jSDHFLgAMtIL0XkwisqLGhW0159SJCrrIk6r4zwRbzbsQ=w71-h78-no?authuser=0'
,icon_size=(60, 60))

a03 = folium.features.CustomIcon('https://lh3.googleusercontent.com/LUuKwUhGD2GOj2hqWzdMVjZuY2aGwkHY2Bi0Kvw3gQIKiHpKUny6Dnex4aTZ4GJOyhHbhJNGb3lV2ihYX0fapJQWvMBhjH5gUQx6-SvdaIc-rdq8t-e4LJ8_nqPWTXUZ8tNL67FsUQgaOKFB5-gnJPku5l2TY7iKKfyvK48UPhaKJisbowQV1Su3VlceHNaSZVhh5VAAlWppuuMDQCTWyIPKzC6Ov_UzBmaEflMiEuj1TUBLMa9CUIeQy198WVMRFiRLXFYt4DKG1eHpioawbvIQhjTUz417r4tZ4apQCQI7zjkI-3enGTbwFug34HtH2ap-IQGxAR3rTbPbbbkTMzfkxI3q3KnjJtCf7qwc4eF6BSCKTW5NUXYiZpJUKjJX3uad3NqlXG1_bG7bRRqTPFC7UrLHQptflw0nTAMJKmsS7khBTcDe7S-Q82okDZTY22Pcm5oDwRoLqXjxTWeq57MN4pq9B15B1krKSXHRtqlpq7mtCUGDNv9aY537-I5yoBwG9Bzcxh-tZ5QsLmrCVtm7m46fyuIaEVgcLnTKI9gWHTqvuIGZo-O8fCSDRF4Hc6zmONhV5KT-Rz0qHcWHuBqAx1rjuyYXcl0Oo7VhwCzBOkXI79pNzzGsZxmxLPzL3Occy2ApqN4tWyg7aB_CXB4hVgcQKE6CGKXd1Uqamx5bC1_w0H3zsJRiW9BHUg=w71-h78-no?authuser=0'
,icon_size=(60, 60))

a04 = folium.features.CustomIcon('https://lh3.googleusercontent.com/nmeXEkxRYRFT1f5M5VgWxF2CSpmplAD28EzzJPg-SpoKiH2_04kS00aLTalz4reqO7tv0OwPDenoeiCm2l4hFytP8c0QD_PcZ9ZkfBTNKNHCASo8inpw0OX57fydYq1vqrW6bTOVnCyjWJTVrDKC_j3NPHok8CjLElMqXM_QqvMmuQgb7a3gsGk8k4aC-9vpSOLhali5kuTMsSceEKT1XkoYIi1ghMwIQeF4IdVM9dW9-1nXYzsSTOfiwv9u4g3cTgJoccm1wATNCPMOoWU3XzBvGfMMhd57LIO5r3CgLFENdzuWZ4bBC4Vp7Wth4542AsX0hRFYIAv1mFE-N6NKVIBDxPOkM-xnONsWj2Eo5Vu3B3sTVyWuXqcLDwWdP6a7_4r_Bp-vEluc-kutmyyiCm54JFkFW31g0eJa9sLwDfsjWy5_kagsoF1MvjqsEyCshJfrU_Vy1l7gAkMf3CZe7EFrZqtr3bu1FjUM04TDoWtOfovMBML0IfoJLBl-281WeEBShqfRMdNcUjDXWVHRZrxCN4mFCOlx_sisMkB-_tg_mJcUca4cOqd__srQ3dN8vlUDc4_wTzQOmDW6_HaA7NYhy9dio1NDT8HDsbazKMm9eEYIU1B2Oh1HgAR1KJAE_3AfJe0WAksNvF5PsV0vBL6gEyYv40fAmL7btubHIwiCKH1L4iOqDeybrkk2RQ=w75-h78-no?authuser=0'
,icon_size=(60, 60))

a19 = folium.features.CustomIcon('https://lh3.googleusercontent.com/T3CFNI2WrFq7zpb7wpH2mz52Uu1zxyJCAbF9fHZc0iwZD40geYxIp2Es5zl_sXQaVcTZ1UsCLJNJNW3tlHmEdse6ErT6oR4SNtPFDu_huL0UObubBvojwg0yo_Qu1wWfyA93h5tlQIzWtIYkPgrbONQKMY1S4BRSjtOQKyZEJEW0ZJopDAgu2R126tmPOd_2S984nxuYq4WvMLUl0Xr2kZDcbQE6mJuy8o_ELntko6RSRYlt-hHHs6W0RNdSCcqkIBJGCu1B28nk3GXOfYPTj9frK77ocoLbWT7nyTIzJgwhHZWX5NiD-s_dy18o_3bt-mC6MnVxBgn8UFsBkCBWBCPlK3AQuqz2vh4hFnmQYPbyH1DgzqMIT-YXmZndRqah_8ta53tI7Q5iATpX3UR130GN74KTXyopcIUn-x3nkla-hJzYKloSeLd7-6QEOl-nNDpbInkMyoKVg6TJ_DZgz2x0WKPEN7ASOciN-KD1pnkANBLKcVGaWrIgWur5TeAiBHG6f26nZl1QI6cqKHDBpZoIhq6Lljgv-5BXVyLFJSB-rYqhHcrh5qBr9o056K-gPMqb9kTZod2IJKKsxhGcRLZ2HLvvbvpbFMt_YZ6rr0-qwL5s_nXZ78qoUen7vB9bV6PvXWWd8OoHMvdPFTviuAL--REKvt4Cebum5jbzq37DY1JSDkd_wa3N84ChHA=w75-h78-no?authuser=0'
,icon_size=(60, 60))

a09 = folium.features.CustomIcon('https://lh3.googleusercontent.com/gys19hchQJviq7G5j7fL-OxiO4SpRBQGP8PMPL0cy7JJam66BB1VYNTZ4tMguI7EWfB_T3ebgm771ePKNwCq_AWoE503BEfg3Kxx1JroUWFnCf2H7dzAU61wSRB6J4TCMu_kdmhYX-8NiZw42fPVJvjqUsiwL_5959BecCQM6QgK0EBmoqmwZmKQA7a2d83mjtounxvJpq_GhUeC2QlIjGLaBBYaHKrmjnoMM7QrZmvRbfxTGdtawlLIAU_IODz4hlht8nHXLU1SfUJ3XwGC_6rw65jGS2tuumebVyBbp0d-7RHccdd-otISvGt0Fy02YimuL4snTfzrI0k54-vusIGUXrg4UWD1X5fqsxcZ5BGQ6y1Q1pUcBape_GG0uB4xQxXjwo_YG5qMdNJaKFGqPTDhPm-VSIyNKZ_E25EVormIkI9N-l5szXVZA3OuVb1jNyttsC86OiDOUpszOIUsCYfy6cSEhTcM1nEq9yY0vc_EE1f7NuqkpqKSBalY3-KDhX8yZN6M7vwLYualg_k18PFBTgsGMSu9rtYot9no2qO5XiI1KnFy8qO75CpLvANl0JAPUKfTB-FgZRh_9BqeRqxxjhYwOJr_KQFPgwbaeCwJPhMVAa7N2_cP9Vq8MFt0hk-TkzLANv68atUxNwCa4-K_EwX2mxL-IK6QmFHAyGwFR2MqQouQ0lj2jxTldA=w75-h78-no?authuser=0'
,icon_size=(60, 60))

a05 = folium.features.CustomIcon('https://lh3.googleusercontent.com/7mbdCcRlNLzGj6esmm09T8qyFllBC_giHoBMgBfcNbr4s25BYK5looExnh_C8nkkezdvzX7aAQSnjHUDWuNS5_31X53UmD1BRIjpmlBhsGIjLGb8hvd2Bu5M72LVHPlPXIkMU0-KjRnE7eR8fIY5xDLccLQszkDPTOSAU58PbaxncurBA0oZ0qXBlI282quXHDA6RlElac95Z4efaPpMqqh54u1RuIkmQ1APH3AprGrsw7124lEcwKW-f5UebT4bG2YQ21o2lpUEh6tBOY2CCHcO1kAThfE5sbrNvqzNUlh_WDIcVP2jNecmatZ31WPtme4UiPthnKBIqLjn_AQNaUG8uYrBTnEf0E3sFStvA40uGu0LwTTZSjBIJbCGq0wKuK5P3SIGr8ezC50Vll0a_-Xo80BAZCQT2qhPgcJt8EZDJSv2388khNFrgkMHwYHANysOp9S9e7SLcgyB8vsEb-1gwD65c0kzZFDVfeZReeQv5p8NpnbOLQwpRMuUiBzlucs3FWrTpY9kZPuAmmzf03rP7x7UvuaV4AV_J-2YMXhnei8mJ2qnaYAbVJRWC5Or8uaare_8klm20--vF2Pln3a5qItXVhaQPd4Q7Qa2J5zX6ewZX-52R7n-a_zSWxJED2nYu3CjFgi7hAP1Yv91xCH4_h614-iMDNQIPQPf_jUNrADNFa3cU4Ulrn-OKA=w75-h78-no?authuser=0'
,icon_size=(60, 60))

f01 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3d9q8n8RGsUuwXL8Qu_C9XsthHftXicz6R9t13whHOXcWK0iXkwUXS6Feu8QrHyXdWgJGtELnDJEgj4qOcwD7-ZAHBDPHIkBNoe6mBKdqUkoMMaydf4uL_Q9amMFa2FJAb8kpDasZRXbiQXYPZHq754iQ=w75-h78-no?authuser=0', 
                                 icon_size=(55, 55))
f17 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3eFTHt-8ARHGf6uleVgVhk0Fno8oa0PVf-dkUkzAr2XopK6zCtg5RFipgShZ8pFbAV1hV28le9Mt0XYCztZQTwFt6TMdE4-wj-EtI5p9jwcdtDoKsEs4Fp58TFSI-N46aZmWkipvDfWABOjicWxh8GDuA=w75-h78-no?authuser=0', 
                                 icon_size=(55, 55))
f03 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3f8kg1tQCCH7L0UvBqVfYt9d5T8q9GsOc2NGrRhA0vkz-TRuX6CZ4t5-0in1ZRYH9k99MnTmjJ58KRtzWtOHvQ6nZlBOG-2didEKk25dIc-pyH3MnunvwRxnkrvQdrtKgULa7JPxU20Ivwl21OhJXy2ug=w75-h78-no?authuser=0', 
                                 icon_size=(55, 55))
f04 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3ccwUMtghTXikVA141KK-3i_iM9SCuO-M65uzFcZXGGUdB2BSXSs33fD6Xi9ozVfq5KVDNOq33cEJRWE4TboTRI4QSwT4DD8P3GtQJ2TC4XNE8sVh4AgKfyAGJk7HTcGaaL3UEG97nyRP60WBf5Bqoh-A=w75-h78-no?authuser=0', 
                                 icon_size=(55, 55))
f19 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3dc5-uCDwt3rpWmfRMkfPlhuA5xoU8sBnSbCTxQgN86ULKe8hOfFtPE24VUpCVllQgsIdIAboFHqTs1lFbTNLZ5T7ZfBiLHrTcXXRVfTE_PG2L0CqhdpsX1MDgXvvhFUw_kOfC0gWy8J6Fd1eFLQNhlMw=w75-h78-no?authuser=0', 
                                 icon_size=(55, 55))
f09 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3fnQV_YfsPHDlasSSznQ-odyW61MARSA00O6iUTH_Vemq8xtJkP8lUun1NrukNIcbHdr7Hs1Ce25GzXO8xsZWLErauvw43MIuFFc5ON3b4u-v-nYne8RXON6-OjEFzB3nmWF8X1zDML4h7EiNDOf9nyCA=w75-h78-no?authuser=0', 
                                 icon_size=(55, 55))
f05 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3f5co4HwJLLkO806QKi07V5QN_aE7p5GA2BzOocM79ysNjWsUUwH2iKFR3ep5KOfcjIAUyEtm80Ku937RnrCkaNcEK5eTgjw6VMjpv4uOyBnIiGu9Upwxmnoxk49SFahvglMsE401v38Bb7FfcpNmy25A=w75-h78-no?authuser=0', 
                                 icon_size=(55, 55))


#Escolher MARKER aberto(Verde) ou fechado(cinza) - MANHA

if hora in range(7, 11) and dia in range(0,5):
    ubsf01 = a01
    ubsf17 = a17
    ubsf03 = a03
    ubsf04 = a04
    ubsf19 = a19
    ubsf09 = a09
    ubsf05 = a05
    
else:
    ubsf01 = f01
    ubsf17 = f17
    ubsf03 = f03
    ubsf04 = f04
    ubsf19 = f19
    ubsf09 = f09
    ubsf05 = f05

folium.Marker([-4.276056,-41.790067], popup=ppp01, tooltip=ttp01, icon = ubsf01).add_to(cluster)
folium.Marker([-4.283263,-41.771249], popup=ppp17, tooltip=ttp17, icon = ubsf17).add_to(cluster)
folium.Marker([-4.298168,-41.773053], popup=ppp03, tooltip=ttp03, icon = ubsf03).add_to(cluster)
folium.Marker([-4.291159,-41.772228], popup=ppp04, tooltip=ttp04, icon = ubsf04).add_to(cluster)
folium.Marker([-4.272012,-41.784157], popup=ppp19, tooltip=ttp19, icon = ubsf19).add_to(cluster)
folium.Marker([-4.265230,-41.784434], popup=ppp09, tooltip=ttp09, icon = ubsf09).add_to(cluster)
folium.Marker([-4.258300,-41.774830], popup=ppp05, tooltip=ttp05, icon = ubsf05).add_to(cluster)


#BLOCO TARDE
#Url dos icones: Icones a(aberto), f(fechado)
iconsizea = (60, 60)

a15 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3d5ghqzImFY7jJthwknBSWZm1h2xs0nFYkQWtO9TsUnbFOe4W3Z9paOLhfzcK4BhgkVx5PtUzd7xIjL6RdJggJBRDDHkq_5yO8UsD3Hrs_IbTnP0WBAd8jR9k1jzkHhWn-cjJF1AJdDl0hZrCgpkzJGtQ=w71-h78-no?authuser=0'
,icon_size = iconsizea)

a02 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3fH_ROmCY8mH8AfA8zqYeE9XXR9Big8AzTCaVGtrwRIg2YOmjiPazol_FnDhu6WQmmRzzujIV1YIdXc0tbHW5HxU6qPV6QJ4dOz78ibyVzJOWIo0ihmH--Whyn5L4WV27d6FbPjknqKnkmDIAw3PrKNtA=w72-h78-no?authuser=0'
,icon_size = iconsizea)

a21 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3dzMmthANNFTbfaQqP6mY1VCHBhwK40sML4WC0znTBdVV0W6Agd-Xv3q0F88QtZHW4SBOQcL6AxJBiAb5P6U1hUVROgzTpUngvHD6XqnmaKko5eyWVAtCl2rlOgVgM2F-5yl3g0iapeMu1S_moiW9JsZQ=w71-h78-no?authuser=0'
,icon_size = iconsizea)

a29 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3c3y-ykroSuuzx9RvFKjX5zyci9BybDkFbS7kSgtvtl85OwOJw3nUG9TObfmFrXOPBncnstETZace16IrDbWrV-USFA8HLszAxXjYtdGOp0ArVSCM2iN0tWSCEIwSPCiffgilppoPr5iL0Mk3xRZpTI-w=w71-h78-no?authuser=0'
,icon_size = iconsizea)

a18 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3dvVeCF5GP4g1vfP0Rd-FZASn_ILaLhkhvpXrNsmQlxMDbAyOgtuJhuDMrGn1KpdPpk7GR07p8M8b9VHv-BenPJRpj9P2mLzDHmG5xY80GlIcSzMfVIqu90XcLh4VrCRpvnlIl2-jVqVl8EuPPi0J4PJA=w72-h78-no?authuser=0'
,icon_size= iconsizea)

a08 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3dAhyzgWRwLGVdSrzHJODZgZdDNftOEvTlU8c-nmxOryT76zAFd40ufNE0qnoEZMVvB8ld9MglUmddDjFXsy48-bcJHH_fU6351pRKcjvas8N20aZYAGiDi2gY3L3SrOExX4VnmzmSPOkoDjHglJgjMSw=w72-h78-no?authuser=0'
,icon_size= iconsizea)

a07 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3eYDvGWSO1see0PS-URluM9OXaERG3JQB__Wz9fboOkX3lB87qd_5ViMtPqxVTG4DETEzw77mcl4oGGi8eUx8DKNPQG_ff5GcigN0wscfx75X1aRYpcvNLjNDJ602Kl4INiMeJ-4UKOd4ICurhF6UvH1A=w71-h78-no?authuser=0'
,icon_size= iconsizea)

a13 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3du93k1933cD7Iw7aVPzhmuFNNmqRZNeY_hijHk-kM7SYB9lDSp0YORdTn8-uTRVd-bs2i4W62ef7u73ykdHS25b0LNQ0VotK4_wL-8D2tWc63CLI2Yp5njE2UNy_lwkUWgg-1NUnyQL1R_81vpHvVCnA=w71-h78-no?authuser=0'
,icon_size= iconsizea)

a06 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3eU-LsijGaX-FH8zyD89yAJ3oHJGaCMDtc0JzMeFBjHnOfFivzZa292yetxvLXBob3ZpClAWX5ouaHnk86S5bXwNUSdUMV6dtcHwAx4_doHkruqrbnFcGQ42IPzbfdQuuM9bAztYxOlg8JOR6Zh4s6smw=w72-h78-no?authuser=0'
,icon_size= iconsizea)


#Fechado
iconsizef = (55, 55)

f15 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3eSS5v13WA8of5eDsD-xZRLqLkgDMCLb8NpdQhOueMIRREXUM8PiwSCVgMq--EzcC1tVyYsnQIi4kdtZ74rcqu6RePdFox2xKGmjS8-yHFmm_XrzVyQRQV7JPY2cFYz9xdJ9GNxoCTeqUDlV_I3_GdNBA=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f02 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3fSA6IHqn-BaFrRYk7AYd18L-1FhOeS86mYWN9NWgiE67KYHWv9K_y6uFLHuEzrmKe3x8K_Lm-uFzwMjJIb51m_kkW6FmlM_F2R3SmSJMcZdo51dwvjIIY6r1v4F4Y5zIZ12wA9F1X6QzzTIwxDQ8Ye8Q=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f21 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3fb3LWNQvfzxYXvYkJXm7YL5lwcPd0RqjQ_qSMEYJbX3jEjk2xaOZ8-Z-fzhCwZelIrkn5eqN6WxfRfj_cNO_fc-1mL0gqk4txVnwPhLhWdOxs_uAAAkmyFX4qBS1S_dYQfe-zeQ-xRty7KCJlVeGh9hQ=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f29 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3co8QZKSwo-eTf65N7A-zRdeXaBYl8XVC0GTTj_QY7HpOgHppGEdA4s7pfb1fR4hQ-aUGmIHwSpzt3JNb04LUPCDeKBcVL_VRv5AMGcqC00ctDHcsp_n92qJCXooQnpHy-eaYj1cAymVZE-B5NTgmezog=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f18 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3f9rgSD1r25CoiZnDMpQ_90fM9d3ToAW6zVHJvkmMIfbX6xHwCyY70nDLt_f_D5AbXfN-U9-e1ziwUbcp8DcmOZTmnwzPBBDnbTk91-Ghdq-pK48uhEY971gxsdOozg1B6JHQdXSQCOtsgJCovZrki6xg=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f08 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3fnXrF8Fl--GY3it3N4jU7PmKzihfbXYv3yHhpmQClbfq3RZ3IV1jN8uF3sVzoBg2KK1dgkMz-sP0eH_WHH3XuaB7zZPYv_6T12fIY0tNTaZA1rQxy1g-WXub2b3sY148PMPqIXuvPqPA8BlZVSMVz-Fw=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f07 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3cESkK-gxPdH2u-wyWNZcyxr-0dN7gjuejygbb-Zh3jgGBMDHIckIXO7fFMUjI-EfI_QWNqRPZ_Ns4VrhWXYi5gn07tUGrol80vvE8ACbyqSw3brlERndF_apfvbm7_ihwuVJo_2ZWipn--iCeK2MbdDw=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f13 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3ded0iFmR9a7yWNpSc1rIwpkY9fcXgxzSGfvbTKfnQePec8uX0xNKVNI74rTbPpI0Xo0bTWoNEvru_5orgrA-sPNecIVHik-aUznr4AT-QAs8zxmX3gQ_NEBPUw5CLU9m-49BTPl2dfRSPdIAKSHqv8NQ=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)
f06 = folium.features.CustomIcon('https://lh3.googleusercontent.com/pw/ACtC-3fE4Gy2NEqHm5RZzOg7eXnssn0Ex-Ma1JzIY2fIlFT1iH9ZDWR4oc5CVsarxpu5254UUtmKwh7mlo2nUtdCf2DjZ3FCgxM2kbcbkxJdQbwXtoIWK1f4ZDH8gTnqziE66BVWPHUPCsdlOUGQy6EXB11e3g=w75-h78-no?authuser=0', 
                                 icon_size=iconsizef)

#Escolher MARKER aberto ou fechado - TARDE

if hora in range(13, 17) and dia in range(0,5):
    ubsf15 = a15
    ubsf02 = a02
    ubsf21 = a21
    ubsf29 = a29
    ubsf18 = a18
    ubsf08 = a08
    ubsf07 = a07
    ubsf13 = a13
    ubsf06 = a06

else:
    ubsf15 = f15
    ubsf02 = f02
    ubsf21 = f21
    ubsf29 = f29
    ubsf18 = f18
    ubsf08 = f08
    ubsf07 = f07
    ubsf13 = f13
    ubsf06 = f06

folium.Marker([-4.291829,-41.774533], popup = ppp21, tooltip=ttp21, icon = ubsf21).add_to(cluster)
folium.Marker([-4.267368,-41.758368], popup = ppp29, tooltip=ttp29, icon = ubsf29).add_to(cluster)
folium.Marker([-4.272481,-41.779542], popup = ppp18, tooltip=ttp18, icon = ubsf18).add_to(cluster)
folium.Marker([-4.283875,-41.783126], popup = ppp08, tooltip=ttp08, icon = ubsf08).add_to(cluster)
folium.Marker([-4.264629,-41.775409], popup = ppp07, tooltip=ttp07, icon = ubsf07).add_to(cluster)
folium.Marker([-4.269237,-41.787985], popup = ppp13, tooltip=ttp13, icon = ubsf13).add_to(cluster)
folium.Marker([-4.257852,-41.768271], popup = ppp06, tooltip=ttp06, icon = ubsf06).add_to(cluster)
folium.Marker([-4.304620,-41.772350], popup = ppp15, tooltip=ttp15, icon = ubsf15).add_to(cluster)
folium.Marker([-4.271438,-41.791732], popup = ppp02, tooltip=ttp02, icon = ubsf02).add_to(cluster)

#Tempo Integral

a20 = folium.features.CustomIcon('https://lh3.googleusercontent.com/BPN1b1myVtu9QMVeEGrx6ctrRIxD4vZ_rjlal-oIb7fzowjctFKgEKnzjVWekWswHMqrqPCmFwyOC1bgGiEjoWPpopeuu8ND6H359K5y8Fb_5Z6RXEXfVcuwY_uLdt6rZaxfFd0QjnLs-sKIGao1xZ8RCOcv2LIcduwXB4RCvUU2sgLgJh7k2K2AXzaM4xL51LRd8VmGjN9T9ke5BWmzlEFBTvQYo9oPtMsRNG4x4oTUr8MP-yao7rIZdqbbc5a3qUkp3PdXa6IYwoBCXO1zDnHqqTWjm-61ZqbfaIR-oYVP-a5rgBoqcmx-RySRpGFqt1y02TeNQxcBFzhwc106zbooGHJNVMMeYUH0YRzj626fBDd-im6hodn6cyOkDJffbp5CcBerhPkHJiR4b6KmEdSDzBqf7n4_Zxh3PnGNd6iPlwZZVpJTGSqJIfvBknYN0oiXJ1VMY54PpDOyXlAdL5jgHF8LTXzw5u6RIzjEJ8altqmIOPbcJ7sWOgOOSgeITEK3TGdakD0MZ3jftOZshKas9sW7FtMSd1XlYhZ3ixUpioeldCwLG2hV_dMZBU92s9SR1DPGi7Aa3rRa75FvmH8450qDYdkJZ4uDFU18Pk9LlAMMhlyW6KLaFnEIf0flqlUloXoiReRTz2K-Mzym5UNg2AsqLmoMqnU5ovszSjGfmmHnGf5-POnvAUbZZQ=w98-h82-no?authuser=0'
,icon_size=(75, 65))
f20 = folium.features.CustomIcon('https://lh3.googleusercontent.com/bZu6KNSlrfo8Nwz1IiQ4tY8hoXw7WuVP_r9TLui8JWKgz4Mz8PGfD79tUNKjdRTmVU-HHREzrpPfg_ef88loWj6EECjeGXzb3pPP6IlaD6abnmZjdUQBlG_A8a1Ffqhr1QAZjAic0qvLdA-0TG_KS4wUsXO9_q3pg_5cwGDV4P07fH_cXxtGj4kfR0C79O52ZNQ0YujSFEp24ZrVqRW0bxiZvlk8loqIcrPaY4lbCxK13WFN5KvMwarQIc2rJ4g90VaVcRlupig3xA4PxtXL9MsLpLla3yKkAg9WVdQLyXnTTbuM7rTV9QrAGmXndpKPa0mPuKapaLVeT8kzce0N5KzQ_-xQSqXuqjuqdcuqTnMNyAwAU45NACChJWBOuXCnu3bSpcneznMEqhF6aFmpZZfb8mADsBfn6XbRXew5oQRAtPdAO5C9SUIQyq_lu3pO0ioqRqRKww3tDyfEqm5JBUsw0HrAB1vjVFKZrGNY7fWnrRQjJVBRWJSPELOirqvKsnbJhJpw0bkJsdGT0ZvJPp7GF3P9QwkCfDlZmYyKA8I1yArHmzGYNLgNxCuf_JC2Y4nglvQ_63COHVpAnZdDtV0WSKtHGElRKKNIzAssF7svlTU7LD_YYMnS1NWHvkseyuRjPE5pVeR3Eeh567tpylMtHj-7vDYgG8I4fSY_fOPI-TyXvvvoK8egwyJyUg=w104-h79-no?authuser=0'
,icon_size=(70, 60))

if hora in range(7, 17) and dia in range(0,5):
    ubsf20 = a20
else:
    ubsf20 = f20

folium.Marker([-4.272683,-41.762476], popup=ppp20, tooltip = ttp20, icon = ubsf20).add_to(cluster)
LocateControl(auto_start=True).add_to(m)


#Legenda

from branca.element import Template, MacroElement
template = """
{% macro html(this, kwargs) %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Draggable - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <script>
  $( function() {
    $( "#maplegend" ).draggable({
                    start: function (event, ui) {
                        $(this).css({
                            right: "auto",
                            top: "auto",
                            bottom: "auto"
                        });
                    }
                });
});

  </script>
</head>
<body>

 
<div id='maplegend' class='maplegend' 
    style='position: absolute; z-index:9999; border:2px solid gray; background-color:rgba(255, 255, 255, 0.8);
     border-radius:6px; padding: 10px; font-size:14px; right: 20px; bottom: 20px;'>
     
<div class='legend-title'>Legenda</div>
<div class='legend-scale'>
  <ul class='legend-labels'>
    <li><span style='background:#00ff00;opacity:0.7;'></span>UBSF Aberta</li>
    <li><span style='background:#777;opacity:0.7;'></span>UBSF Fechada</li>

  </ul>
</div>
</div>
 
</body>
</html>

<style type='text/css'>
  .maplegend .legend-title {
    text-align: left;
    margin-bottom: 5px;
    font-weight: bold;
    font-size: 90%;
    }
  .maplegend .legend-scale ul {
    margin: 0;
    margin-bottom: 5px;
    padding: 0;
    float: left;
    list-style: none;
    }
  .maplegend .legend-scale ul li {
    font-size: 80%;
    list-style: none;
    margin-left: 0;
    line-height: 18px;
    margin-bottom: 2px;
    }
  .maplegend ul.legend-labels li span {
    display: block;
    float: left;
    height: 16px;
    width: 40px;
    margin-right: 5px;
    margin-left: 0;
    border: 1px solid #999;
    }
  .maplegend .legend-source {
    font-size: 80%;
    color: #777;
    clear: both;
    }
  .maplegend a {
    color: #777;
    }
</style>
{% endmacro %}"""

macro = MacroElement()
macro._template = Template(template)

m.get_root().add_child(macro)

m

"""#Mostrar lat lon do usuário."""

import IPython
html_code = \
'''

<!DOCTYPE html>
<html>
<body>
<p id="demo"></p>

<script>
var x = document.getElementById("demo");

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else { 
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
  x.innerHTML = "Latitude: " + position.coords.latitude + 
  "<br>Longitude: " + position.coords.longitude;
}
getLocation()
</script>
</body>
</html>
'''

display(IPython.display.HTML(html_code))

"""#Importando bibliotecas de rotas e widgets"""

!pip install openrouteservice ortools
from openrouteservice import client as client
# Bibliotecas dos widgets
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
from IPython.display import display
from IPython.display import clear_output

"""## MAPA PARA A ROTA
Apenas as unidades abertas aparecem na caixa de seleção.
"""

locais1 = [('UBSF-18 CENTRO', [-4.272481 , -41.779542, ubsf18, ttp18, ppp18]),
('UBSF-01 VISTA ALEGRE', [-4.276056 , -41.790067, ubsf01,ttp01, ppp01]),
('UBSF-17 FONTE DOS MATOS', [-4.283263, -41.771249, ubsf17, ttp17, ppp17]),
('UBSF-03 PRADO' ,[-4.298168 , -41.773053, ubsf03, ttp03, ppp03]),
('UBSF-04 PACIENCIA', [-4.291159 , -41.772228, ubsf04, ttp04, ppp04]),
('UBSF-19 ESTACAO', [-4.272012 , -41.784157, ubsf19, ttp19, ppp19]),
('UBSF-09 FLORESTA', [-4.26523 , -41.784434, ubsf09, ttp09, ppp09]),
('UBSF-05 RECREIO', [-4.2583 , -41.77483, ubsf05, ttp05, ppp05])]

locais2 = [('UBSF-21 PACIENCIA 2', [-4.291829 , -41.774533, ubsf21, ttp21, ppp21]),
('UBSF-29 PETECAS III IV', [-4.272683 , -41.762476, ubsf29, ttp29, ppp29]),
('UBSF-08 GERMANO', [-4.283875 , -41.783126, ubsf08, ttp08, ppp08]),
('UBSF-07 CAIXA DAGUA', [-4.264629 , -41.775409, ubsf07, ttp07, ppp07]),
('UBSF-13 MATADOURO', [-4.269237 , -41.787985, ubsf13, ttp13, ppp13]),
('UBSF-06 SAO JOAO', [-4.257852 , -41.768271, ubsf06, ttp06, ppp06]),
('UBSF-15 CONJUNTO', [-4.30462 , -41.77235, ubsf15, ttp15, ppp15]),
('UBSF-02 SANTA MARIA', [-4.271438 , -41.791732, ubsf02, ttp02, ppp02]),
('UBSF-20/24 PETECAS/CRIOULI', [-4.267368 , -41.758368, ubsf20, ttp20, ppp20])]

locais3 = ['Unidades Fechadas']

if hora in range(7, 11) and dia in range(0,5):
    locais = locais1   
elif hora in range(13, 16) and dia in range(0,5):
    locais = locais2
else:
  locais = locais3

#estilo da rota
style = {'color': '#fd2b85'}
# API do openroute services
api_key = '5b3ce3597851110001cf6248ce9c379b4c0446d6abf7ea0d29cd0da0'
clnt = client.Client(key=api_key) # Create client with api key

w = widgets.Dropdown(
    options= locais,
    description='UBSF:',
)
def on_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        clear_output(wait=True)
        display(w)
        valor = w.value
        print(valor)
        lat1 = valor[0]
        lon1 = valor[1]
        ubs = valor[2]
        mapa = folium.Map (location = [-4.275,-41.78],
               tiles = 'OpenStreetMap',
               zoom_start =  13.5,
               attr = 'Colaboradores do OpenStreetMap e Alunos de CartoUFPR/ Dados IPPUC' 
               )
        request_params = {'coordinates': [[lon1, lat1], [-41.77286170000001,-4.2696983]],
                'format_out': 'geojson',
                'profile': 'driving-car',
                'preference': 'shortest',
                'instructions': 'false',}
        route_normal = clnt.directions(**request_params)
        folium.features.GeoJson(data=route_normal,
                        name='Rota entre os pontos',
                        style_function=lambda x: style,
                        overlay=True).add_to(mapa)
        coordenadas = [[lat1,lon1], [-4.2696983,-41.77286170000001]]
        folium.Marker([valor[0],valor[1]],icon=valor[2], tooltip=valor[3], popup=valor[4]).add_to(mapa)
        LocateControl(auto_start=True).add_to(mapa)
        mapa.fit_bounds(coordenadas)
        display(mapa)
w.observe(on_change)
display(w) 

#Ajuda
#As rotas não se apagam a cada nova requisição